FROM node:24

EXPOSE 3000/tcp 3001/tcp 7777/tcp

WORKDIR /app

RUN apt-get update && \
    apt-get install -y nginx \
    libx11-xcb1 \
    libxrandr2 \
    libgconf-2-4 \
    libnss3 \
    libasound2 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libxss1 \
    libxcomposite1 \
    libgtk-3-0 \
    chromium \
    git \
    --no-install-recommends && \
    npm install pm2 -g && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . .

# Copy development nginx config and entrypoint
COPY nginx.dev.conf ./nginx.dev.conf
COPY entrypoint.dev.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

WORKDIR /app/be

ENTRYPOINT [ "/app/entrypoint.sh" ]
