version: '3.8'

services:
  microbook-maker:
    image: dovieuu/microbook-maker:latest
    ports:
      - 7777:80
    volumes:
      - mbm-generated:/app/be/generated
      - mbm-uploads:/app/be/uploads

volumes:
  mbm-generated:
  mbm-uploads:
