# Development docker-compose with hot reload
services:
  microbook-maker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7777:7777"  # Full application (nginx proxy) - MAIN ACCESS POINT
      - "3000:3000"  # Vite dev server (direct access, optional)
      - "3001:3001"  # Backend API (direct access, optional)
    volumes:
      # Mount entire source directories for hot reload
      - ./fe:/app/fe
      - ./be:/app/be
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
